[package]
name = "bracketroguelike"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["ch*"]

[workspace.dependencies]
bracket-lib = { git = "https://github.com/amethyst/bracket-lib.git" }
specs = { version = "0.20.0", features = ["specs-derive"] }
