[workspace]
resolver = "2"
members = ["roguelike/*"]

[workspace.dependencies]
bracket-lib = { git = "https://github.com/amethyst/bracket-lib.git" }
specs = { version = "0.20.0", features = ["specs-derive"] }
